on:
  push:
    branches:
    - master
  - name: Markup Link Checker (mlc)
  # You may pin to the exact commit or the version.
  # uses: becheran/mlc@609f5037a477d17a9020acc1d97f1568494d2972
  uses: becheran/mlc@v0.14.0
  with:
    # arguments
    args: # optional, default is ./
